# Generated by Django 6.0 on 2025-12-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cari Adı')),
            ],
            options={
                'verbose_name': 'Cari / Firma',
            },
        ),
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Alan Adı')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=50, unique=True, verbose_name='Müşteri Kodu')),
                ('name', models.CharField(max_length=200, verbose_name='Müşteri Adı')),
                ('city', models.CharField(max_length=50, verbose_name='İl')),
                ('district', models.CharField(max_length=50, verbose_name='İlçe')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Açık Adres')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('authorized_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yetkili Kişi')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Enlem')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Boylam')),
                ('cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customercari', verbose_name='Cari / Firma')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
