# Generated by Django 6.0 on 2025-12-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Alan Adı')),
                ('options', models.TextField(blank=True, null=True, verbose_name='Seçenekler (Virgülle ayırın)')),
            ],
        ),
    ]
