# Generated by Django 6.0 on 2026-01-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_site_title'),
        ('customers', '0003_customer_tenant_alter_customer_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Firma'),
        ),
    ]
