# Generated by Django 6.0 on 2026-01-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_site_title'),
        ('customers', '0004_alter_customer_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sys_id',
            field=models.PositiveIntegerField(blank=True, help_text='Firma içinde otomatik atanır (1, 2, 3...)', null=True, verbose_name='Sistem ID'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'sys_id')},
        ),
    ]
