# Generated by Django 6.0 on 2025-12-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='FieldOps Platform', max_length=200, verbose_name='Site Başlığı')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_branding/', verbose_name='Site Logosu')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Ana Renk (Primary)')),
                ('secondary_color', models.CharField(default='#6c757d', max_length=7, verbose_name='İkincil Renk (Secondary)')),
            ],
            options={
                'verbose_name': 'Site Ayarı',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
