# Generated by Django 6.0 on 2025-12-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Ayar Anahtarı (Kod)')),
                ('label', models.CharField(max_length=200, verbose_name='Ekranda Görünen İsim')),
                ('value', models.TextField(verbose_name='Değer')),
                ('category', models.CharField(choices=[('general', 'Genel Sistem Ayarları'), ('visit', 'Ziyaret & Konum Ayarları'), ('user', 'Kullanıcı & Personel Ayarları'), ('notification', 'Bildirim Ayarları')], default='general', max_length=20)),
                ('input_type', models.CharField(choices=[('text', 'Yazı'), ('number', 'Sayı'), ('bool', 'Açık/Kapalı (Checkbox)')], default='text', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Sistem Ayarı',
                'verbose_name_plural': 'Sistem Ayarları',
                'ordering': ['category', 'id'],
            },
        ),
    ]
