# Generated by Django 6.0 on 2025-12-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsetting',
            options={'ordering': ['category', 'id'], 'verbose_name': 'Sistem Ayarı (YENI)', 'verbose_name_plural': 'Sistem Ayarları'},
        ),
    ]
