# Generated by Django 6.0 on 2025-12-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_tenant_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='Rotexia Platform', max_length=200, verbose_name='Site Başlığı'),
        ),
    ]
