# Generated by Django 6.0 on 2026-01-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='menu_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Hangi menülerin görünür olacağını belirler', verbose_name='Menü Ayarları'),
        ),
    ]
