# Generated by Django 6.0 on 2026-01-06 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_menu_settings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.TextField(help_text='Virgülle ayırarak birden fazla e-posta adresi ekleyebilirsiniz', verbose_name='Kime')),
                ('cc_email', models.TextField(blank=True, help_text='Virgülle ayırarak birden fazla e-posta adresi ekleyebilirsiniz', null=True, verbose_name='CC')),
                ('subject', models.CharField(max_length=500, verbose_name='Konu')),
                ('body', models.TextField(verbose_name='Mail İçeriği')),
                ('selected_reports', models.JSONField(default=dict, help_text='Hangi raporların gönderileceği', verbose_name='Seçili Raporlar')),
                ('merge_reports', models.BooleanField(default=False, help_text='İşaretlenirse tüm raporlar tek Excel dosyasında sheet olarak gönderilir', verbose_name='Raporları Birleştir')),
                ('report_start_date', models.DateField(verbose_name='Rapor Başlangıç Tarihi')),
                ('report_end_date', models.DateField(verbose_name='Rapor Bitiş Tarihi')),
                ('send_start_date', models.DateField(help_text='Hangi tarihte gönderilmeye başlansın', verbose_name='Gönderim Başlangıç Tarihi')),
                ('send_end_date', models.DateField(blank=True, help_text='Mail gönderiminin son tarihi (opsiyonel)', null=True, verbose_name='Gönderim Bitiş Tarihi')),
                ('period', models.CharField(choices=[('daily', 'Her Gün'), ('weekly', 'Her Hafta'), ('monthly', 'Her Ay')], max_length=20, verbose_name='Periyot')),
                ('day_option', models.CharField(choices=[('every_day', 'Her Gün'), ('monday', 'Her Pazartesi'), ('first_of_month', 'Her Ayın İlk Günü')], max_length=20, verbose_name='Hangi Gün')),
                ('send_time', models.TimeField(help_text='Raporun gönderileceği saat (örn: 22:00)', verbose_name='Gönderim Saati')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Gönderim Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automated_emails', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_emails', to='core.tenant', verbose_name='Firma')),
            ],
            options={
                'verbose_name': 'Otomatik Mail',
                'verbose_name_plural': 'Otomatik Mailler',
                'ordering': ['-created_at'],
            },
        ),
    ]
