# Generated by Django 6.0 on 2026-01-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_automatedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='superuser_plain_password',
            field=models.CharField(blank=True, help_text='Şifre düz metin olarak saklanır (sadece görüntüleme için)', max_length=128, null=True, verbose_name='Superuser Şifresi'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='superuser_username',
            field=models.CharField(blank=True, help_text="Bu firmaya ait superuser'ın kullanıcı adı", max_length=150, null=True, verbose_name='Superuser Kullanıcı Adı'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='category',
            field=models.CharField(choices=[('general', 'Genel Sistem Ayarları'), ('visit', 'Ziyaret & Konum Ayarları'), ('user', 'Kullanıcı & Personel Ayarları'), ('notification', 'Bildirim Ayarları'), ('email', 'E-posta Ayarları')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='input_type',
            field=models.CharField(choices=[('text', 'Yazı'), ('number', 'Sayı'), ('bool', 'Açık/Kapalı (Checkbox)'), ('password', 'Şifre (Gizli)')], default='text', max_length=10),
        ),
    ]
