# Generated by Django 6.0 on 2026-01-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_superuser_plain_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Boş ise global/şablon ayarı (Rotexia), dolu ise firma-specific ayar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.tenant', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Ayar Anahtarı (Kod)'),
        ),
        migrations.AlterUniqueTogether(
            name='systemsetting',
            unique_together={('key', 'tenant')},
        ),
    ]
