# Generated by Django 6.0 on 2025-12-26 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_tenant_subscription'),
        ('customers', '0002_customerfielddefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant', verbose_name='Kiracı'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Harita koordinatı (örn: 41.0082)', null=True, verbose_name='Enlem'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Harita koordinatı (örn: 28.9784)', null=True, verbose_name='Boylam'),
        ),
    ]
