# Generated by Django 6.0 on 2025-12-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ziyaret Tipi Adı')),
            ],
            options={
                'verbose_name': 'Ziyaret Tipi',
                'verbose_name_plural': 'Ziyaret Tipleri',
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_code', models.CharField(max_length=50, verbose_name='Personel Kodu (Merch)')),
                ('active_days', models.JSONField(default=list, verbose_name='Aktif Günler')),
                ('visit_duration', models.IntegerField(blank=True, default=0, null=True, verbose_name='Ziyaret Süresi (Dk)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Rota Planı',
                'verbose_name_plural': 'Rota Planları',
            },
        ),
        migrations.CreateModel(
            name='VisitTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merch_code', models.CharField(max_length=50, verbose_name='Atanan Personel')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Planlanan Tarih')),
                ('cycle_day', models.IntegerField(verbose_name='Döngü Günü (1-28)')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandı'), ('missed', 'Ziyaret Edilmedi')], default='pending', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('visit_note', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Müşteri')),
                ('visit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='field_operations.visittype', verbose_name='Ziyaret Tipi')),
            ],
            options={
                'verbose_name': 'Ziyaret Görevi',
                'verbose_name_plural': 'Ziyaret Görevleri',
                'ordering': ['-planned_date'],
            },
        ),
    ]
