# Generated by Django 6.0 on 2026-01-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_site_title'),
        ('field_operations', '0002_reportrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_records', to='core.tenant', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='routeplan',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_plans', to='core.tenant', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='visittask',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_tasks', to='core.tenant', verbose_name='Firma'),
        ),
    ]
