# Generated by Django 6.0 on 2025-12-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Alan Adı')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Kullanıcı Özel Alan Tanımı',
                'verbose_name_plural': 'Kullanıcı Özel Alan Tanımları',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Özel Veriler'),
        ),
    ]
