# Generated by Django 6.0 on 2026-01-02 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_authoritynode_multi_and_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_key', models.CharField(max_length=100, verbose_name='Menü Anahtarı')),
                ('menu_label', models.CharField(max_length=200, verbose_name='Menü Etiketi')),
                ('can_view', models.BooleanField(default=False, verbose_name='Görebilir')),
                ('can_edit', models.BooleanField(default=False, verbose_name='Düzenleyebilir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Menü İzni',
                'verbose_name_plural': 'Kullanıcı Menü İzinleri',
                'ordering': ['menu_key'],
                'unique_together': {('user', 'menu_key')},
            },
        ),
    ]
