# Generated by Django 6.0 on 2026-01-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_site_title'),
        ('users', '0005_usermenupermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermenupermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authoritynode',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authority_nodes', to='core.tenant', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.tenant', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='usermenupermission',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='core.tenant', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='core.tenant', verbose_name='Firma'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Rol Adı'),
        ),
        migrations.AlterUniqueTogether(
            name='usermenupermission',
            unique_together={('user', 'menu_key', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('name', 'tenant')},
        ),
    ]
