# Generated by Django 6.0 on 2026-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_site_title'),
        ('users', '0006_alter_usermenupermission_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(max_length=20, verbose_name='Kullanıcı Kodu'),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('user_code', 'tenant')},
        ),
    ]
