# Generated by Django 6.0 on 2026-01-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_alter_sitesetting_site_title'),
        ('users', '0007_make_user_code_tenant_unique'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(fields=('user_code', 'tenant'), name='unique_user_code_per_tenant'),
        ),
    ]
