# Generated by Django 6.0 on 2026-01-03 21:21

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_add_menu_settings'),
        ('users', '0008_make_user_code_tenant_unique_v2'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_user_code_per_tenant',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bu kullanıcı adı zaten kullanılıyor.'}, help_text='Otomatik oluşturulur: {firma}_{kod}', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Kullanıcı Adı'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('user_code', 'tenant'), name='unique_user_code_per_tenant'),
        ),
    ]
