# Generated by Django 6.0 on 2025-12-25 12:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'Kısa Metin'), ('select', 'Seçmeli (Evet/Hayır)'), ('multi_select', 'Çoklu Seçim'), ('photo', 'Fotoğraf'), ('number', 'Sayısal'), ('date', 'Tarih'), ('location', 'Konum (GPS)')], default='text', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('visible_if_value', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='forms.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='forms.question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Form Başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('frequency_type', models.CharField(choices=[('always', 'Her Ziyarette (Standart)'), ('once', 'Sadece Bir Kez'), ('daily', 'Günde 1 Kez'), ('weekly', 'Haftada 1 Kez'), ('monthly', 'Ayda 1 Kez'), ('first_day_month', 'Ayın İlk Günü'), ('specific_days', 'Belirli Günlerde (Pzt, Sal...)')], default='always', max_length=20, verbose_name='Doldurma Sıklığı')),
                ('active_days', models.JSONField(blank=True, default=list, verbose_name='Aktif Günler')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('target_caris', models.ManyToManyField(blank=True, to='customers.customercari', verbose_name='Hangi Carilerde Geçerli?')),
            ],
            options={
                'verbose_name': 'Form / Anket',
                'verbose_name_plural': 'Formlar',
            },
        ),
    ]
