# Generated by Django 6.0 on 2025-12-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target_roles',
            field=models.ManyToManyField(blank=True, to='users.userrole', verbose_name='Hangi Roller Görecek?'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='forms.survey'),
        ),
    ]
