# Generated by Django 6.0 on 2025-12-26 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_operations', '0001_initial'),
        ('forms', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='parent_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='question',
            name='visible_if_value',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='active_days',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='frequency_type',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='target_caris',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='target_roles',
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Kısa Yazı'), ('textarea', 'Uzun Yazı'), ('photo', 'Fotoğraf'), ('select', 'Seçim Kutusu')], default='text', max_length=20, verbose_name='Cevap Tipi'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=500, verbose_name='Soru Metni'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Zorunlu mu?'),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Seçenek Metni'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Anket Başlığı'),
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Metin Cevabı')),
                ('answer_photo', models.ImageField(blank=True, null=True, upload_to='survey_photos/', verbose_name='Fotoğraf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.question')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='field_operations.visittask')),
            ],
        ),
    ]
