# Generated by Django 6.0 on 2025-12-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_question_max_photos_question_min_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='forms.question', verbose_name='Bağlı Olduğu Soru'),
        ),
        migrations.AddField(
            model_name='question',
            name='trigger_answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Tetikleyici Cevap'),
        ),
    ]
