# Generated by Django 6.0 on 2025-12-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_question_parent_question_question_trigger_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi?'),
        ),
        migrations.AddField(
            model_name='survey',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi'),
        ),
    ]
