# Generated by Django 6.0 on 2025-12-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerfielddefinition'),
        ('forms', '0009_remove_survey_target_customers_survey_filter_caris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target_customers',
            field=models.ManyToManyField(blank=True, related_name='old_targets', to='customers.customercari'),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Kısa Yazı'), ('textarea', 'Uzun Yazı'), ('photo', 'Fotoğraf'), ('select', 'Seçim Kutusu')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_photos',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_photos',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='parent_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_questions', to='forms.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='trigger_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitiş'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Başlangıç'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='survey_photos/'),
        ),
        migrations.AlterField(
            model_name='surveyanswer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
