# Generated by Django 6.0 on 2025-12-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_survey_target_customers_alter_question_input_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dependency_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='forms.question', verbose_name='Bağlı Olduğu Soru'),
        ),
        migrations.AddField(
            model_name='question',
            name='dependency_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tetikleyen Cevap Değeri'),
        ),
    ]
