# Generated by Django 6.0 on 2025-12-26 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_question_dependency_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='filter_users',
            field=models.ManyToManyField(blank=True, related_name='surveys_as_user', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı Filtresi'),
        ),
        migrations.AddField(
            model_name='survey',
            name='user_custom_filters',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Kullanıcı Özel Alan Filtreleri'),
        ),
    ]
