# Generated by Django 6.0 on 2026-01-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_sitesetting_site_title'),
        ('forms', '0012_survey_filter_users_survey_user_custom_filters'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.tenant', verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_answers', to='core.tenant', verbose_name='Firma'),
        ),
    ]
