# Generated by Django 6.0 on 2026-01-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_survey_tenant_surveyanswer_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='answer_video',
            field=models.FileField(blank=True, null=True, upload_to='survey_videos/', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.CharField(choices=[('text', 'Kısa Yazı'), ('textarea', 'Uzun Yazı'), ('photo', 'Fotoğraf'), ('select', 'Seçim Kutusu'), ('video', 'Video'), ('location', 'Konum')], default='text', max_length=20),
        ),
    ]
