# Generated by Django 6.0 on 2025-12-26 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_systemsetting_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Plan Adı')),
                ('plan_type', models.CharField(choices=[('basic', 'Temel'), ('pro', 'Profesyonel'), ('enterprise', 'Kurumsal')], max_length=20, verbose_name='Plan Tipi')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Aylık Fiyat')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yıllık Fiyat')),
                ('max_users', models.IntegerField(default=5, verbose_name='Maksimum Kullanıcı Sayısı')),
                ('max_customers', models.IntegerField(default=50, verbose_name='Maksimum Müşteri Sayısı')),
                ('max_tasks_per_month', models.IntegerField(default=500, verbose_name='Aylık Maksimum Görev')),
                ('max_storage_gb', models.IntegerField(default=5, verbose_name='Maksimum Depolama (GB)')),
                ('has_advanced_reports', models.BooleanField(default=False, verbose_name='Gelişmiş Raporlar')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='API Erişimi')),
                ('has_custom_branding', models.BooleanField(default=False, verbose_name='Özel Markalama')),
                ('has_priority_support', models.BooleanField(default=False, verbose_name='Öncelikli Destek')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Abonelik Planı',
                'verbose_name_plural': 'Abonelik Planları',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Şirket Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL Slug')),
                ('email', models.EmailField(max_length=254, verbose_name='İletişim E-postası')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name='Abonelik Başlangıcı')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='Abonelik Bitişi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenant_logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#0d6efd', max_length=7, verbose_name='Ana Renk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan', verbose_name='Abonelik Planı')),
            ],
            options={
                'verbose_name': 'Kiracı (Tenant)',
                'verbose_name_plural': 'Kiracılar (Tenants)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('cancelled', 'İptal Edildi'), ('expired', 'Süresi Doldu'), ('trial', 'Deneme')], default='trial', max_length=20, verbose_name='Durum')),
                ('start_date', models.DateTimeField(verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tutar')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ödeme Yöntemi')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fatura No')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan', verbose_name='Plan')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.tenant', verbose_name='Kiracı')),
            ],
            options={
                'verbose_name': 'Abonelik',
                'verbose_name_plural': 'Abonelikler',
                'ordering': ['-created_at'],
            },
        ),
    ]
