# Generated by Django 6.0 on 2025-12-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('forms', '0003_alter_questionoption_options_alter_survey_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='target_customers',
            field=models.ManyToManyField(blank=True, to='customers.customercari', verbose_name='Hedef Müşteriler'),
        ),
        migrations.AddField(
            model_name='survey',
            name='target_roles',
            field=models.ManyToManyField(blank=True, to='users.userrole', verbose_name='Hedef Roller'),
        ),
    ]
