# Generated by Django 6.0 on 2025-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_survey_target_customers_survey_target_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='max_photos',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Max. Fotoğraf'),
        ),
        migrations.AddField(
            model_name='question',
            name='min_photos',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Min. Fotoğraf'),
        ),
    ]
