# Generated by Django 6.0 on 2025-12-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('forms', '0007_survey_end_date_survey_is_active_survey_start_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Özel Filtreler'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_customers',
            field=models.ManyToManyField(blank=True, to='customers.customercari'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_roles',
            field=models.ManyToManyField(blank=True, to='users.userrole'),
        ),
    ]
