# Generated by Django 6.0 on 2025-12-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('forms', '0008_survey_custom_filters_alter_survey_target_customers_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='target_customers',
        ),
        migrations.AddField(
            model_name='survey',
            name='filter_caris',
            field=models.ManyToManyField(blank=True, related_name='surveys_as_cari', to='customers.customercari', verbose_name='Cari Filtresi'),
        ),
        migrations.AddField(
            model_name='survey',
            name='filter_customers',
            field=models.ManyToManyField(blank=True, related_name='surveys_as_customer', to='customers.customer', verbose_name='Müşteri Filtresi'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='custom_filters',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='target_roles',
            field=models.ManyToManyField(blank=True, to='users.userrole', verbose_name='Rol Filtresi'),
        ),
    ]
